-- 📄Crear la base de datos MySQL
CREATE DATABASE IF NOT EXISTS PetHub;
USE PetHub;

-- 👩🏻‍🦰 Crear la tabla de usuarios
CREATE TABLE users (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL ENUM('Admin', 'User', 'Specialist') NOT NULL DEFAULT 'User',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE  --False 0 True 1
);

-- 🐶 Crear la tabla de mascotas
CREATE TABLE pets (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SPECIE ENUM('perro', 'gato', 'ave', 'otro') NOT NULL,
    AGE INT NOT NULL,
    USER_ID INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE, --False 0 True 1
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE
);

-- 📅 Crear la tabla de citas
CREATE TABLE appointments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE DATETIME NOT NULL,    
    TYPE ENUM('consulta', 'vacunación', 'baño', 'otro') NOT NULL,
    PET_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    SPECIALIST_ID INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE, --False 0 True 1
    FOREIGN KEY (PET_ID) REFERENCES pets(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (SPECIALIST_ID) REFERENCES users(ID) ON DELETE CASCADE
);